baseURL: https://echocat.org/
languageCode: en-us
title: echocat

disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS

params:
  summary: echocat is an open source association with focus to support software and information technology operations projects.
